highlighter: pygments
markdown: rdiscount
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - highlight
    - tables
    - strikethrough
    - fenced_code_blocks
permalink: /:year/:month/:title/
#url: http://blog.sevenche.com
author: zhengkang
#pygments: true
paginate: 24
